languageCode = "pt-BR"
title = "Lucas dos Santos Abreu"
baseurl = "/"
theme = "smol"

disqusShortname = "lucas-dos-santos-abreu"
enableEmoji = true

[Params]
  dateFmt = "2006-01-02"

[author]
  name = "Lucas dos Santos Abreu"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Resume"
  weight = 1
  identifier = "Resume"
  url = "/resume"

[[menu.main]]
  name = "Twitter"
  weight = 2
  identifier = "twitter"
  url = "https://twitter.com/LucasSantAbreu"

[[menu.main]]
  name = "GitHub"
  weight = 3
  identifier = "github"
  url = "https://github.com/lucassabreu"

[[menu.main]]
  name = "Medium"
  weight = 4
  identifier = "medium"
  url = "https://medium.com/@lucassabreu"

[[menu.main]]
  name = "LinkedIn"
  weight = 5
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/lucassantosabreu"

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    codeFences = true
